version: "3"
services:
  node-app:
    ports:
      - "8000:8000"
    deploy:
      restart_policy:
        condition: on-failure
    build:
      context: .
      args:
        - NODE_ENV=${NODE_ENV}
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
    command: npm run dev